### ISSUE TITLE
Smart mode behaves like indent mode?

### ISSUE THREAD

**Issue by knubie** [gpanders/nvim-parinfer#6]
Hey there, I'm just checking out the plugin, but I can't seem to get smart mode to work as I expected it to. It seems to operate like indent mode. I've recorded a couple of demos comparing the plugin with the parinfer demo online.

https://user-images.githubusercontent.com/431251/144957899-cac6f05b-4c7a-4f02-b85d-5b91049c62f9.mov

https://user-images.githubusercontent.com/431251/144957946-f4834e74-95bf-4e94-955c-d534a5683762.mov

**Comment by gpanders** [comment]
This should be resolved when #8 is merged. If you're up for it, please checkout the `changes` branch locally and let me know if you find any bugs or unexpected behavior.

**Comment by knubie** [comment]
Thanks for the update @gpanders, but I'm still seeing the same behavior as in the video I posted.

**Comment by gpanders** [comment]
Are you sure you checked out the `changes` branch? If I replicate your example it works as expected.

**Comment by knubie** [comment]
I'm pretty sure I was on `changes`, but I just tried again on `master` and it seems to work now. I'll switch to using this plugin full time and let you know if I run into any more issues. Thanks!

**Comment by nstgc** [comment]
I see this issue was resolved by a PR in February and the latest version is from April. Is this expected to work? I installed with vim-plugged, but Smart acts like Indent, and Paren acts like the plug in is disabled.
